interfaces:

  leaf1:
    lo:
      ipv6: "fd::1:1/128"
      ipv4: "172.16.0.1/32"

    swp1:
      alias: "To spine 1"

    swp2:
      alias: "To spine 2"

  leaf2:
    lo:
      ipv6: "fd::1:2/128"
      ipv4: "172.16.0.2/32"
      
    swp1:
      alias: "To spine 1"

    swp2:
      alias: "To spine2"

  leaf3:
    lo:
      ipv6: "fd::1:3/128"
      ipv4: "172.16.0.3/32"

    swp1:
      alias: "To spine 1"

    swp2:
      alias: "To spine2"

  leaf4:
    lo:
      ipv6: "fd::1:4/128"
      ipv4: "172.16.0.4/32"

    swp1:
      alias: "To spine 1"

    swp2:
      alias: "To spine2"

bgp:

  leaf1:
    asn: "64601"
    fabric_ports: ["swp1", "swp2"]
    #server_ports: ["swp3", "swp4"]

  leaf2:
    asn: "64602"
    fabric_ports: ["swp1", "swp2"]
    #server_ports: ["swp3", "swp4"]

  leaf3:
    asn: "64603"
    fabric_ports: ["swp1", "swp2"]
    #server_ports: ["swp3", "swp4"]

  leaf4:
    asn: "64604"
    fabric_ports: ["swp1", "swp2"]
    #server_ports: ["swp3", "swp4"]