---
before_script:
   - cd /Users/plumbis/vagrant/interop-2016/
   - vagrant destroy -f

stages:
   - lint
   - behave
   - cleanup

lint:
   stage: lint
   script:
      - bash linter.sh

launch_lab:
   stage: behave
   script:
      - cd /Users/plumbis/vagrant/interop-2016/validation
      - vagrant destroy -f
      - vagrant up --color
      - sleep 10
      - behave --force-color
      - sleep 10

flush_vagrant:
   stage: cleanup
   script:
      - vagrant destroy -f
