---
before_script:
   - cd /Users/plumbis/vagrant/interop-2016/
   - vagrant destroy -f

Lint_and_Launch:
   script:
      - bash linter.sh
      - cd /Users/plumbis/vagrant/interop-2016/validation
      - vagrant up --color
      - sleep 10
      - behave --force-color
      - sleep 10
